dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide_1 owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
  - psql -U postgres -c "ALTER ROLE decide Superuser"
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
script:
  - cd decide
  - cp travis_local_settings.py local_settings.py
  - coverage run --branch --source=. ./manage.py test postproc
  - coverage xml
  - python-codacy-coverage -r coverage.xml
deploy:
  provider: heroku
  app: decide-full-tinto-postproc
  strategy: git
  apikey: $HEROKU_AUTH_TOKEN